# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.test import TestCase

# Create your tests here.
masir_categories = [
        'Digital-Accessories',
        'Kids',
        'Makeup',
        'Bed-Bath',
        'Bicycle',
        'Camera',
        'Car-Equipment',
        'Carpet',
        'Car',
        'Kids',
        'Clean',
        'Computer-parts',
        'Car-Equipment',
        'Decorative',
        'Gift',
        'Kids',
        'Electrical-Personal',
        'Toy',
        'Film',
        'Hand-Tool',
        'Health',
        'Handcraft',
        'Bed-Bath',
        'Health',
        'Home-Electrical-Appliance',
        'Home-Kitchen-Appliance',
        'Jewerly',
        'Laptop',
        'General-Home',
        'Mobile',
        'Training',
        'Music-Tools',
        'Music',
        'Hand-Tool',
        'Office-Machines',
        'Perfume',
        'Kids',
        'Men-Accessories',
        'Electrical-Tool',
        'Travel',
        'Publications',
        'Kids',
        'General-Home',
        'Software',
        'Sport-Tools',
        'Sport-Shoes',
        'Sport-Clothes',
        'staitionery',
        'Glass',
        'Tablet',
        'Toy',
        'Travel',
        'Video-Audio',
        'Watch-Clock',
        'Motorbike'
    ]