# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bamilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField()),
                ('new_price', models.IntegerField(default=0)),
                ('old_price', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(default=0)),
                ('discount_percent', models.FloatField()),
                ('address', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Digikala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_persian_name', models.TextField()),
                ('item_english_name', models.TextField()),
                ('new_price', models.IntegerField(default=0)),
                ('old_price', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(default=0)),
                ('discount_percent', models.FloatField()),
                ('address', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DigikalaIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='DigikalaUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Torob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField()),
                ('new_price', models.IntegerField(default=0)),
                ('old_price', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(default=0)),
                ('discount_percent', models.FloatField()),
                ('address', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TorobShopId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopid', models.IntegerField()),
            ],
        ),
    ]
