# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0002_auto_20170918_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='digikalaids',
            name='discount_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='digikalaids',
            name='discount_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='digikalaids',
            name='item_english_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='digikalaids',
            name='item_persian_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='digikalaids',
            name='new_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='digikalaids',
            name='old_price',
            field=models.IntegerField(default=0),
        ),
    ]
