# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0003_auto_20170919_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigikalaIds2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_persian_name', models.TextField(default='')),
                ('item_english_name', models.TextField(default='')),
                ('new_price', models.IntegerField(default=0)),
                ('old_price', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(default=0)),
                ('discount_percent', models.FloatField(default=0)),
                ('url', models.URLField(max_length=1000)),
            ],
        ),
    ]
