# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0004_digikalaids2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DigikalaIds2',
        ),
    ]
