# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0005_delete_digikalaids2'),
    ]

    operations = [
        migrations.AddField(
            model_name='bamilo',
            name='item_image',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
