# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0006_bamilo_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bamilo',
            name='classification',
            field=models.TextField(default=''),
        ),
    ]
