# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0009_auto_20170926_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digikala',
            name='classification_1',
        ),
        migrations.RemoveField(
            model_name='digikala',
            name='classification_2',
        ),
        migrations.RemoveField(
            model_name='digikalaids',
            name='classification_1',
        ),
        migrations.RemoveField(
            model_name='digikalaids',
            name='classification_2',
        ),
    ]
