# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0010_auto_20170926_0525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digikalaids',
            old_name='url',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='digikalaids',
            old_name='item_english_name',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='digikala',
            name='item_english_name',
        ),
        migrations.AddField(
            model_name='digikala',
            name='item_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bamilo',
            name='item_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='digikala',
            name='item_persian_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='digikalaurls',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='torob',
            name='item_name',
            field=models.TextField(default=''),
        ),
    ]
