# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 13:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0011_auto_20171004_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='bamilo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bamiloids',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='digikala',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='digikalaids',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='digikalaurls',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
