# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 13:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0014_auto_20171004_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bamilo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 13, 26, 40, 116921)),
        ),
        migrations.AlterField(
            model_name='bamiloids',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 13, 26, 40, 118915)),
        ),
        migrations.AlterField(
            model_name='digikala',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 13, 26, 40, 117533)),
        ),
        migrations.AlterField(
            model_name='digikalaids',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 13, 26, 40, 118480)),
        ),
        migrations.AlterField(
            model_name='digikalaurls',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 13, 26, 40, 117962)),
        ),
    ]
