# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0017_auto_20171004_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='torob',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='torobids',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='torobshopid',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
