# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0018_auto_20171004_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='bamiloids',
            name='last_flag',
            field=models.IntegerField(default=0),
        ),
    ]
