# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0019_bamiloids_last_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bamiloids',
            name='last_flag',
            field=models.IntegerField(default=0),
        ),
    ]
