# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0022_auto_20171005_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bamilo',
            old_name='category',
            new_name='categoryfa',
        ),
        migrations.AddField(
            model_name='bamilo',
            name='categoryfa1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bamilo',
            name='categoryfa2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bamilo',
            name='categoryfa3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bamilo',
            name='categoryfa4',
            field=models.TextField(default=''),
        ),
    ]
