# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0025_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
