# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0029_auto_20171012_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_bamilo',
            name='category4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product_bamilo',
            name='category5',
            field=models.TextField(default=''),
        ),
    ]
