# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0031_masir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masir',
            name='masir_cat',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
