# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0032_auto_20171016_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masir',
            name='masir_cat',
            field=models.TextField(default='Other'),
        ),
    ]
