# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0033_auto_20171016_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='BamiloUrlsL1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default='')),
                ('category', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='BamiloUrlsL2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default='')),
                ('category', models.TextField(default='')),
            ],
        ),
    ]
