# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0034_bamilourlsl1_bamilourlsl2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bamilourlsl1',
            old_name='category',
            new_name='category1',
        ),
        migrations.RenameField(
            model_name='bamilourlsl2',
            old_name='category',
            new_name='category1',
        ),
        migrations.AddField(
            model_name='bamilourlsl2',
            name='category2',
            field=models.TextField(default=''),
        ),
    ]
