# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0035_auto_20171018_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='bamiloids',
            name='category1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bamiloids',
            name='category2',
            field=models.TextField(default=''),
        ),
    ]
