# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0036_auto_20171018_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigikalaUrlsL1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default='')),
                ('category1', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='DigikalaUrlsL2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default='')),
                ('category1', models.TextField(default='')),
                ('category2', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='BamiloUrls',
        ),
    ]
