# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_app', '0037_auto_20171018_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_digikala',
            old_name='category',
            new_name='category1',
        ),
    ]
